version: '3.3'

services:
  web:
    build: .
    container_name: vision-invert-web
    restart: unless-stopped
    volumes:
      - ./static:/app/static
    environment:
      - ENV=production
    networks:
      - docker-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.visioninvert.entrypoints=websecure"
      - "traefik.http.routers.visioninvert.rule=Host(`chuyenhinh.xaydungcaogia.com`)"
      - "traefik.http.routers.visioninvert.tls.certresolver=myresolver"
      - "traefik.http.services.visioninvert.loadbalancer.server.port=8000"

networks:
  docker-net:
    external: true
